services:
  webapp:
    build:
      target: development
    environment:
      - FLASK_ENV=development
    volumes:
      - ./app:/usr/src/code/app

volumes:
  db-data:
    external: true
    name: gavmild_db-data