services:
  webapp:
    build:
      target: production
    restart: always
    environment:
      - FLASK_ENV=production
    networks:
      - backend
      - nginx

networks:
  nginx:
    external: true
    name: www_nginx
    aliases:
          - gavmild-webapp