services:
  db:
    image: mariadb:10.9.8-jammy
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend
    environment:
      - MARIADB_DATABASE=gavmild
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/db-password
      - MARIADB_MYSQL_LOCALHOST_USER=1
      - MARIADB_USER=dba
      - MARIADB_PASSWORD_FILE=/run/secrets/dba-password
    secrets:
      - db-password
      - dba-password
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect"]
      start_period: 30s
      timeout: 3s
      interval: 5s
      retries: 5

  webapp:
    build: ./webapp
    restart: always
    environment:
      - PRISJAKT_CLIENT_ID=1517
      - TELEGRAM_GROUP_ID=-4069140153
      - DATABASE_HOST=db:3306/gavmild
    secrets:
      - dba-password
      - flask-secret-key
      - telegram-token
      - bot-api-token
      - prisjakt-secret
    ports:
      - 5005:5005
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./webapp/app:/usr/src/code/app

  telegram:
    build: ./telegram
    restart: always
    secrets:
      - telegram-token
      - bot-api-token
      - openai-token
      - prisjakt-secret
      - prisjakt-id
      - chat-group-id
    ports:
      - 5006:5006

networks:
  backend:

volumes:
  db-data:

secrets:
  db-password:
    file: ./secrets/db_root.txt
  dba-password:
    file: ./secrets/db_dba.txt
  flask-secret-key:
    file: ./secrets/flask-secret-key.txt
  telegram-token:
    file: ./secrets/telegram_token.txt
  bot-api-token:
    file: ./secrets/bot-api-token.txt
  openai-token:
    file: ./secrets/openai-token.txt
  prisjakt-id:
    file: ./secrets/prisjakt-client-id.txt
  prisjakt-secret:
    file: ./secrets/prisjakt-client-secret.txt
  chat-group-id:
    file: ./secrets/chat-group-id.txt